version: '3.4'

services: 

  frontend:
    image: storeimage
    build:
      context: .
      dockerfile: DockerfileStore
    environment: 
      - ProductEndpoint=http://backend:8080
      - ImagePrefix=https://special-fortnight-qpq77v9gjxc44pj-32001.app.github.dev/images
    ports:
      - "32000:8080"
    depends_on: 
      - backend
  backend:
    image: productservice
    build: 
      context: .
      dockerfile: DockerfileProducts
    ports: 
      - "32001:8080"